apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-s3
  namespace: gravitee
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: cnpg-s3
    creationPolicy: Owner
    template:
      data:
        ACCESS_KEY_ID: "{{ .access_key }}"
        ACCESS_SECRET_KEY: "{{ .secret_key }}"
        REGION: garage
  dataFrom:
    - extract:
        key: backup/cnpg
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: garage
  namespace: gravitee
spec:
  retentionPolicy: 7d
  configuration:
    destinationPath: s3://cnpg/gravitee
    endpointURL: http://192.168.10.13:3900
    s3Credentials:
      accessKeyId:
        name: cnpg-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-s3
        key: ACCESS_SECRET_KEY
      region:
        name: cnpg-s3
        key: REGION
    wal:
      compression: gzip
    data:
      compression: gzip
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gravitee-pg-cluster-daily
  namespace: gravitee
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: gravitee-pg-cluster
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
