apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-admin
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: gitea-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: gitea/admin
        property: username
    - secretKey: password
      remoteRef:
        key: gitea/admin
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-pg-app
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: gitea-pg-app
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: gitea
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: gitea/db
        property: password
