apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-ca
  namespace: keycloak
data:
  ad-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDdTCCAl2gAwIBAgIUSYNUsLBoPB2Y7IoIjgZKEGWW6VgwDQYJKoZIhvcNAQEL
    BQAwSjEVMBMGCgmSJomT8ixkARkWBWxvY2FsMRcwFQYKCZImiZPyLGQBGRYHZXhh
    bXBsZTEYMBYGA1UEAwwPZXhhbXBsZS1EQzAxLUNBMB4XDTI2MTAwNzA3MDUxNloX
    DTM2MTAwNDA3MDUxNlowSjEVMBMGCgmSJomT8ixkARkWBWxvY2FsMRcwFQYKCZIm
    iZPyLGQBGRYHZXhhbXBsZTEYMBYGA1UEAwwPZXhhbXBsZS1EQzAxLUNBMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhrgkr5rpEWAAPzxRSb+HHDnpgwBz
    qwje4vRaMv1q2EhgK7LuVD5nQfDG9jODEHTyCC87T6q/cIlNe+ZZgpkXEpPwUJTZ
    SqqUvmjzODCyoV/+9HK9siu1WfWRAe9ReivppklTS5cnUo6U6oOTiA6FJQ+vX42m
    D6uFjtHZIPwP9HgAcquuUzCM6PzlExgRAPUmA41NTYTOFEWs2pIRMxWOFCKpQQGT
    C9XlVw835MSJa6NixgtskVg/PhuoKZazg+7J++yBOydNIfuE5MuIxYGnN6TemHHa
    8MRJ7VivpuV67PP/o5keaDlSWLJ4wca/qqTzQKG7JeI0M1FxOVz+ZPARcwIDAQAB
    o1MwUTAdBgNVHQ4EFgQU3HP9PbsQ1LXlTyIITdLfWlDmgqAwHwYDVR0jBBgwFoAU
    3HP9PbsQ1LXlTyIITdLfWlDmgqAwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B
    AQsFAAOCAQEAGsFzf+XpRxkJ4NiMoH6pPZpLw/aq0ESBGQFWw+duvRf/pZqAnZg6
    1tUYM2UYcTet4WooycHPYxoMO3UBE+7hb+7Mz0xE+nD4nmSfES8MyKMhgs2/ms9x
    kVKloeydv6N1A/MXKjnM5IqRnEh4m0xzB0EEhGSqj/ST6i6fdVj5gfG/d+l/L0ZK
    fRNe2/0Biel0WYdJ0Ob6KiD1qJP84P1X/iMSb3lmfIGgQrGN7ZJupHAIebTehIR6
    6Qxr5NXWws5X80VlwvWzjlxA0IcHJjCn0Cdj/wf6fl08TMClnizTl3F+sdqCW91V
    dRRA1CiQmL1UBjWLH9Afk08i/ozznqxIPA==
    -----END CERTIFICATE-----
