apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wildcard-example-com
  namespace: traefik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: wildcard-example-com
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: tls/wildcard-example-com
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: tls/wildcard-example-com
        property: tls.key
