apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-barman-cloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: plugin-barman-cloud
    targetRevision: 0.8.1
    helm:
      releaseName: plugin-barman-cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
